### ISSUE TITLE
请问使用96版本出现过2周一冻结的情况吗?

### ISSUE THREAD

**Issue by airdm** [DINOREXNB/protocol_version#1]
我使用 90 96 9.0.0 都出现了2周就冻结的情况,你用的怎么样.也是一样的吗?

**Comment by DINOREXNB** [comment]
我现在是Mirai 2.16.0搭配xzhouqd/qsign:core-1.1.9签名服务
9.0.0貌似无法使用
8.9.96版本目前确实会出现不定期冻结的情况...
可能是最近tx又加大打击第三方bot力度了吧
